In [3]:
import pandas as pd
import requests

Using the code from the lesson as a guide, create a dataframe named items that has all of the data for items.

In [10]:
base_url = "http://python.zach.lol"
response = requests.get(base_url)
response.json()

{'api': '/api/v1', 'help': '/documentation'}

In [11]:
response = requests.get(base_url + "/documentation")
response.json().keys()
print(response.json()["status"])
print(response.json()["payload"])

ok

The API accepts GET requests for all endpoints, where endpoints are prefixed
with

    /api/{version}

Where version is "v1"

Valid endpoints:

- /stores[/{store_id}]
- /items[/{item_id}]
- /sales[/{sale_id}]

All endpoints accept a `page` parameter that can be used to navigate through
the results.

In [75]:
response = requests.get(base_url + "/api/v1/items")
response.json().keys()

dict_keys(['payload', 'status'])

In [65]:
response.json()["payload"].keys()

dict_keys(['items', 'max_page', 'next_page', 'page', 'previous_page'])

In [66]:
response.json()["payload"]["max_page"]

3

In [67]:
response.json()["payload"]

{'items': [{'item_brand': 'Riceland',
   'item_id': 1,
   'item_name': 'Riceland American Jazmine Rice',
   'item_price': 0.84,
   'item_upc12': '35200264013',
   'item_upc14': '35200264013'},
  {'item_brand': 'Caress',
   'item_id': 2,
   'item_name': 'Caress Velvet Bliss Ultra Silkening Beauty Bar - 6 Ct',
   'item_price': 6.44,
   'item_upc12': '11111065925',
   'item_upc14': '11111065925'},
  {'item_brand': 'Earths Best',
   'item_id': 3,
   'item_name': 'Earths Best Organic Fruit Yogurt Smoothie Mixed Berry',
   'item_price': 2.43,
   'item_upc12': '23923330139',
   'item_upc14': '23923330139'},
  {'item_brand': 'Boars Head',
   'item_id': 4,
   'item_name': 'Boars Head Sliced White American Cheese - 120 Ct',
   'item_price': 3.14,
   'item_upc12': '208528800007',
   'item_upc14': '208528800007'},
  {'item_brand': 'Back To Nature',
   'item_id': 5,
   'item_name': 'Back To Nature Gluten Free White Cheddar Rice Thin Crackers',
   'item_price': 2.61,
   'item_upc12': '759283100036',
   'item_upc14': '759283100036'},
  {'item_brand': 'Sally Hansen',
   'item_id': 6,
   'item_name': 'Sally Hansen Nail Color Magnetic 903 Silver Elements',
   'item_price': 6.93,
   'item_upc12': '74170388732',
   'item_upc14': '74170388732'},
  {'item_brand': 'Twinings Of London',
   'item_id': 7,
   'item_name': 'Twinings Of London Classics Lady Grey Tea - 20 Ct',
   'item_price': 9.64,
   'item_upc12': '70177154004',
   'item_upc14': '70177154004'},
  {'item_brand': 'Lea & Perrins',
   'item_id': 8,
   'item_name': 'Lea & Perrins Marinade In-a-bag Cracked Peppercorn',
   'item_price': 1.68,
   'item_upc12': '51600080015',
   'item_upc14': '51600080015'},
  {'item_brand': 'Van De Kamps',
   'item_id': 9,
   'item_name': 'Van De Kamps Fillets Beer Battered - 10 Ct',
   'item_price': 1.79,
   'item_upc12': '19600923015',
   'item_upc14': '19600923015'},
  {'item_brand': 'Ahold',
   'item_id': 10,
   'item_name': 'Ahold Cocoa Almonds',
   'item_price': 3.17,
   'item_upc12': '688267141676',
   'item_upc14': '688267141676'},
  {'item_brand': 'Honest Tea',
   'item_id': 11,
   'item_name': 'Honest Tea Peach White Tea',
   'item_price': 3.93,
   'item_upc12': '657622604842',
   'item_upc14': '657622604842'},
  {'item_brand': 'Mueller',
   'item_id': 12,
   'item_name': 'Mueller Sport Care Basic Support Level Medium Elastic Knee Support',
   'item_price': 8.4,
   'item_upc12': '74676640211',
   'item_upc14': '74676640211'},
  {'item_brand': 'Garnier Nutritioniste',
   'item_id': 13,
   'item_name': 'Garnier Nutritioniste Moisture Rescue Fresh Cleansing Foam',
   'item_price': 6.47,
   'item_upc12': '603084234561',
   'item_upc14': '603084234561'},
  {'item_brand': 'Pamprin',
   'item_id': 14,
   'item_name': 'Pamprin Maximum Strength Multi-symptom Menstrual Pain Relief',
   'item_price': 7.54,
   'item_upc12': '41167300121',
   'item_upc14': '41167300121'},
  {'item_brand': 'Suave',
   'item_id': 15,
   'item_name': 'Suave Naturals Moisturizing Body Wash Creamy Tropical Coconut',
   'item_price': 9.11,
   'item_upc12': '79400847201',
   'item_upc14': '79400847201'},
  {'item_brand': 'Burts Bees',
   'item_id': 16,
   'item_name': 'Burts Bees Daily Moisturizing Cream Sensitive',
   'item_price': 5.17,
   'item_upc12': '792850014008',
   'item_upc14': '792850014008'},
  {'item_brand': 'Ducal',
   'item_id': 17,
   'item_name': 'Ducal Refried Red Beans',
   'item_price': 1.16,
   'item_upc12': '88313590791',
   'item_upc14': '88313590791'},
  {'item_brand': 'Scotch',
   'item_id': 18,
   'item_name': 'Scotch Removable Clear Mounting Squares - 35 Ct',
   'item_price': 4.39,
   'item_upc12': '21200725340',
   'item_upc14': '21200725340'},
  {'item_brand': 'Careone',
   'item_id': 19,
   'item_name': 'Careone Family Comb Set - 8 Ct',
   'item_price': 0.74,
   'item_upc12': '41520035646',
   'item_upc14': '41520035646'},
  {'item_brand': 'Usda Produce',
   'item_id': 20,
   'item_name': 'Plums Black',
   'item_price': 5.62,
   'item_upc12': '204040000000',
   'item_upc14': '204040000000'}],
 'max_page': 3,
 'next_page': '/api/v1/items?page=2',
 'page': 1,
 'previous_page': None}

In [76]:
items = pd.DataFrame(response.json()["payload"]["items"])
items

,item_brand,item_id,item_name,item_price,item_upc12,item_upc14
0,Riceland,1,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,Caress,2,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
2,Earths Best,3,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139
3,Boars Head,4,Boars Head Sliced White American Cheese - 120 Ct,3.14,208528800007,208528800007
4,Back To Nature,5,Back To Nature Gluten Free White Cheddar Rice ...,2.61,759283100036,759283100036
5,Sally Hansen,6,Sally Hansen Nail Color Magnetic 903 Silver El...,6.93,74170388732,74170388732
6,Twinings Of London,7,Twinings Of London Classics Lady Grey Tea - 20 Ct,9.64,70177154004,70177154004
7,Lea & Perrins,8,Lea & Perrins Marinade In-a-bag Cracked Pepper...,1.68,51600080015,51600080015
8,Van De Kamps,9,Van De Kamps Fillets Beer Battered - 10 Ct,1.79,19600923015,19600923015
9,Ahold,10,Ahold Cocoa Almonds,3.17,688267141676,688267141676
10,Honest Tea,11,Honest Tea Peach White Tea,3.93,657622604842,657622604842
11,Mueller,12,Mueller Sport Care Basic Support Level Medium ...,8.40,74676640211,74676640211
12,Garnier Nutritioniste,13,Garnier Nutritioniste Moisture Rescue Fresh Cl...,6.47,603084234561,603084234561
13,Pamprin,14,Pamprin Maximum Strength Multi-symptom Menstru...,7.54,41167300121,41167300121
14,Suave,15,Suave Naturals Moisturizing Body Wash Creamy T...,9.11,79400847201,79400847201
15,Burts Bees,16,Burts Bees Daily Moisturizing Cream Sensitive,5.17,792850014008,792850014008
16,Ducal,17,Ducal Refried Red Beans,1.16,88313590791,88313590791
17,Scotch,18,Scotch Removable Clear Mounting Squares - 35 Ct,4.39,21200725340,21200725340
18,Careone,19,Careone Family Comb Set - 8 Ct,0.74,41520035646,41520035646
19,Usda Produce,20,Plums Black,5.62,204040000000,204040000000

In [81]:
response = requests.get(base_url + "/api/v1/items?page=2")
items = pd.concat([items,pd.DataFrame(response.json()["payload"]["items"])], ignore_index=True)

In [82]:
response = requests.get(base_url + "/api/v1/items?page=3")
items = pd.concat([items,pd.DataFrame(response.json()["payload"]["items"])], ignore_index=True)
items

,item_brand,item_id,item_name,item_price,item_upc12,item_upc14
0,Riceland,1,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,Caress,2,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
2,Earths Best,3,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139
3,Boars Head,4,Boars Head Sliced White American Cheese - 120 Ct,3.14,208528800007,208528800007
4,Back To Nature,5,Back To Nature Gluten Free White Cheddar Rice ...,2.61,759283100036,759283100036
5,Sally Hansen,6,Sally Hansen Nail Color Magnetic 903 Silver El...,6.93,74170388732,74170388732
6,Twinings Of London,7,Twinings Of London Classics Lady Grey Tea - 20 Ct,9.64,70177154004,70177154004
7,Lea & Perrins,8,Lea & Perrins Marinade In-a-bag Cracked Pepper...,1.68,51600080015,51600080015
8,Van De Kamps,9,Van De Kamps Fillets Beer Battered - 10 Ct,1.79,19600923015,19600923015
9,Ahold,10,Ahold Cocoa Almonds,3.17,688267141676,688267141676
10,Honest Tea,11,Honest Tea Peach White Tea,3.93,657622604842,657622604842
11,Mueller,12,Mueller Sport Care Basic Support Level Medium ...,8.40,74676640211,74676640211
12,Garnier Nutritioniste,13,Garnier Nutritioniste Moisture Rescue Fresh Cl...,6.47,603084234561,603084234561
13,Pamprin,14,Pamprin Maximum Strength Multi-symptom Menstru...,7.54,41167300121,41167300121
14,Suave,15,Suave Naturals Moisturizing Body Wash Creamy T...,9.11,79400847201,79400847201
15,Burts Bees,16,Burts Bees Daily Moisturizing Cream Sensitive,5.17,792850014008,792850014008
16,Ducal,17,Ducal Refried Red Beans,1.16,88313590791,88313590791
17,Scotch,18,Scotch Removable Clear Mounting Squares - 35 Ct,4.39,21200725340,21200725340
18,Careone,19,Careone Family Comb Set - 8 Ct,0.74,41520035646,41520035646
19,Usda Produce,20,Plums Black,5.62,204040000000,204040000000
20,Doctors Best,21,Doctors Best Best Curcumin C3 Complex 1000mg T...,8.09,753950001954,753950001954
21,Betty Crocker,22,Betty Crocker Twin Pack Real Potatoes Scallope...,7.31,16000288829,16000288829
22,Reese,23,Reese Mandarin Oranges Segments In Light Syrup,1.78,70670009658,70670009658
23,Smart Living,24,Smart Living Charcoal Lighter Fluid,5.34,688267084225,688267084225
24,Hood,25,Hood Latte Iced Coffee Drink Vanilla Latte,2.43,44100117428,44100117428
25,Triaminic,26,Triaminic Syrup Night Time Cold & Cough Grape 4oz,0.98,300436344045,300436344045
26,Morton,27,Morton Kosher Salt Coarse,6.01,24600017008,24600017008
27,Usda Produce,28,Guava,7.52,719175900007,719175900007
28,Heinz,29,Heinz Tomato Ketchup - 2 Ct,8.65,13000001038,13000001038
29,Petmate,30,Petmate Booda Bones Steak Bacon & Chicken Flav...,8.39,723503568678,723503568678
30,Zhenas Gypsy Tea,31,Zhenas Gypsy Tea Herbal Red Tea Sachets Fire L...,4.21,652790100226,652790100226
31,Barefoot,32,Barefoot Pinot Grigio 187,0.68,8500004528,8500004528
32,The First Years,33,Tomy The First Years Gumdrop Orthodontic Pacif...,6.52,71463060078,71463060078
33,Halls,34,Halls Menthol Cough Suppresant/oral Anesthetic...,4.17,312546628694,312546628694
34,Natures Way,35,Natures Way Forskohlii - 60 Ct,5.19,33674100066,33674100066
35,Deerfields Gluten Free,36,Rice Bran Gluten Free Dinner Rolls Plain,7.95,610358991525,610358991525
36,Nakano,37,Nakano Seasoned Rice Vinegar Original,9.59,73575295003,73575295003
37,Sundown Naturals,38,Sundown Naturals Essential Electrolytes Tropic...,3.45,30768540548,30768540548
38,Munchies,39,Munchies Sandwich Crackers Cheddar Cheese On G...,9.02,28400029254,28400029254
39,Amys,40,Amys Light & Lean Spaghetti Italiano,0.60,42272008063,42272008063
40,P.f. Changs,41,P.f. Changs Home Menu Meal For Two Beef With B...,5.62,31000670016,31000670016
41,Moms Best Naturals,42,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115
42,Ferrara,43,Ferrara Vanilla Syrup,8.40,71403000379,71403000379
43,Elmers,44,Elmers Board Mate Dual Tip Glue Pen,7.06,26000001403,26000001403
44,Kelloggs,45,Kelloggs Disney Pixar Cars 2 Cereal,4.40,38000542237,38000542237
45,Mama Marys,46,Pizza Sauce,4.65,35457770664,35457770664
46,Bear Naked,47,Bear Naked Fit Almond Crisp 100 Percent Natura...,7.38,884623708976,884623708976
47,Dove,48,Dove Men + Care Antiperspirant Deodorant Cool ...,3.72,79400271631,79400271631
48,Easy-off,49,Easy-off Oven Cleaner Lemon Scent,9.54,62338879772,62338879772
49,Choice,50,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221

Do the same thing, but for stores.

In [83]:
response = requests.get(base_url + "/api/v1/stores")
response.json()
response.json().keys()
response.json()["payload"].keys()
response.json()["payload"]["stores"]

stores = pd.DataFrame(response.json()["payload"]["stores"])
stores

             store_address   store_city  store_id store_state store_zipcode
0   12125 Alamo Ranch Pkwy  San Antonio         1          TX         78253
1         9255 FM 471 West  San Antonio         2          TX         78251
2  2118 Fredericksburg Rdj  San Antonio         3          TX         78201
3          516 S Flores St  San Antonio         4          TX         78204
4          1520 Austin Hwy  San Antonio         5          TX         78218
5       1015 S WW White Rd  San Antonio         6          TX         78220
6   12018 Perrin Beitel Rd  San Antonio         7          TX         78217
7      15000 San Pedro Ave  San Antonio         8          TX         78232
8       735 SW Military Dr  San Antonio         9          TX         78221
9     8503 NW Military Hwy  San Antonio        10          TX         78231

Extract the data for sales. There are a lot of pages of data here, so your code will need to be a little more complex. Your code should continue fetching data from the next page until all of the data is extracted.

In [ ]:
# response = requests.get(base_url + "/api/v1/sales")
# data = response.json()
# data.keys()
# data["payload"].keys()
# data["payload"]["max_page"]
# data["payload"]["next_page"]
# data["payload"]["page"]
# data["payload"][1]

# response = requests.get(base_url + "/api/v1/sales?page=183")
# data = response.json()
# data.keys()

# maxpage = data["payload"]["max_page"] + 1

# sales = pd.DataFrame()
# for page in range(1,maxpage):
#     response = requests.get(base_url + "/api/v1/sales?page={}".format(page))
#     sale_page = pd.DataFrame(response.json()["payload"]["sales"])
#     sales = pd.concat([sales,sale_page])

# sales

Save the data in your files to local csv files so that it will be faster to access in the future.

In [ ]:
# sales.to_csv('/Users/mists/codeup-data-science/ds-methodologies-exercises/time_series/sales.csv')

In [84]:
sales = pd.read_csv("sales.csv")
sales.drop(columns="Unnamed: 0", inplace=True)
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 5 columns):
item           913000 non-null int64
sale_amount    913000 non-null float64
sale_date      913000 non-null object
sale_id        913000 non-null int64
store          913000 non-null int64
dtypes: float64(1), int64(3), object(1)
memory usage: 34.8+ MB

Combine the data from your three separate dataframes into one large dataframe.

In [25]:
items.head()
stores.head()
sales.head()

   item  sale_amount                      sale_date  sale_id  store
0     1         13.0  Tue, 01 Jan 2013 00:00:00 GMT        1      1
1     1         11.0  Wed, 02 Jan 2013 00:00:00 GMT        2      1
2     1         14.0  Thu, 03 Jan 2013 00:00:00 GMT        3      1
3     1         13.0  Fri, 04 Jan 2013 00:00:00 GMT        4      1
4     1         10.0  Sat, 05 Jan 2013 00:00:00 GMT        5      1

In [26]:
sales.store.value_counts()
stores.store_id.value_counts()

10    1
9     1
8     1
7     1
6     1
5     1
4     1
3     1
2     1
1     1
Name: store_id, dtype: int64

In [86]:
df = sales.merge(stores, left_on="store", right_on="store_id")
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 913000 entries, 0 to 912999
Data columns (total 10 columns):
item             913000 non-null int64
sale_amount      913000 non-null float64
sale_date        913000 non-null object
sale_id          913000 non-null int64
store            913000 non-null int64
store_address    913000 non-null object
store_city       913000 non-null object
store_id         913000 non-null int64
store_state      913000 non-null object
store_zipcode    913000 non-null object
dtypes: float64(1), int64(4), object(5)
memory usage: 76.6+ MB

In [52]:
items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
item_brand    20 non-null object
item_id       20 non-null int64
item_name     20 non-null object
item_price    20 non-null float64
item_upc12    20 non-null object
item_upc14    20 non-null object
dtypes: float64(1), int64(1), object(4)
memory usage: 1.0+ KB

In [60]:
sales.head()

   item  sale_amount                      sale_date  sale_id  store
0     1         13.0  Tue, 01 Jan 2013 00:00:00 GMT        1      1
1     1         11.0  Wed, 02 Jan 2013 00:00:00 GMT        2      1
2     1         14.0  Thu, 03 Jan 2013 00:00:00 GMT        3      1
3     1         13.0  Fri, 04 Jan 2013 00:00:00 GMT        4      1
4     1         10.0  Sat, 05 Jan 2013 00:00:00 GMT        5      1

In [87]:
df = df.merge(items, left_on="item", right_on="item_id")
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 913000 entries, 0 to 912999
Data columns (total 16 columns):
item             913000 non-null int64
sale_amount      913000 non-null float64
sale_date        913000 non-null object
sale_id          913000 non-null int64
store            913000 non-null int64
store_address    913000 non-null object
store_city       913000 non-null object
store_id         913000 non-null int64
store_state      913000 non-null object
store_zipcode    913000 non-null object
item_brand       913000 non-null object
item_id          913000 non-null int64
item_name        913000 non-null object
item_price       913000 non-null float64
item_upc12       913000 non-null object
item_upc14       913000 non-null object
dtypes: float64(2), int64(5), object(9)
memory usage: 118.4+ MB

Acquire the Open Power Systems Data for Germany, which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data here: https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.cs

In [54]:
df_OPS = pd.read_csv('https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv')
df_OPS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 5 columns):
Date           4383 non-null object
Consumption    4383 non-null float64
Wind           2920 non-null float64
Solar          2188 non-null float64
Wind+Solar     2187 non-null float64
dtypes: float64(4), object(1)
memory usage: 171.3+ KB

Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions in the acquire.py file and be able to re-run the functions and get the same data.